### ISSUE TITLE
Project TODO list

### ISSUE THREAD

**Issue by nkmathew** [nkmathew/yasi-sexp-indenter#1]
- [x] Support indentation from stdin/piping
- [x] Write unit tests for all functions in yasi.py and yasi.lsp
- [x] Publish on PyPI
- [x] Remove *original_yasi.py* when all the unit and system tests have been written
- [x] Remove the original CHANGELOG at some point
- [x] Support additional keywords through a **~/lispwords** file like in Dorai's scmindent. In hindsight requiring someone to actually edit the new keywords into the script itself was not the brightest of ideas
- [x] Use OptParser for parsing command line arguments
- [x] Format the command line arguments/flags in a markdown table in README. The current format is too wide for the width Github gives
- [x] Should be able to indent portions/segments of lisp code not just the whole file
- [x] Should guess the Lisp dialect from the file extensions
- [x] Update docstring documentation
- [x] Doesn't handle mixed newlines properly
- [x] Add an option for generating diffs of the original and formatted versions
- [x] Support tabbed indentation
- [x] Vim indentexpr function using yasi for newlisp indentation(seeing other lisp flavours have excellent syntax and indent plugins)
- [x] Try to interface with Sublime Text

**Won't implement:**
- [x] Ability to configure the message output string in .yasirc
- [x] Formatting of several files through basic wildcards
- [x] Demo html page with newlisp-js interpreter
